### ISSUE TITLE
Not working on iPhone 5, iOS 10.3.4

### ISSUE THREAD

**Issue by xseignard** [charpeni/react-native-url-polyfill#190] opened 2020-06-12 13:34 UTC
Hello,
It took me a while to track down a bug, but it leads to your lib, as it's not working on iPhone 5/iOS 10.3.4

Here is the error output:
![Capture d’écran 2020-06-12 à 15 33 53](https://user-images.githubusercontent.com/515603/84508145-273a8180-acc2-11ea-96c0-74d9a0b77f3b.png)

**Comment by charpeni** [comment] 2020-06-15 15:24
What's your React Native version?

**Comment by xseignard** [comment] 2020-06-15 15:35
0.62.2

The plugin works on iPhone 6, iOS 12.3.4

**Comment by charpeni** [comment] 2020-06-26 16:44
Ugh. I've been able to reproduce this.

This is coming from iOS 10 and it must be related to the JavaScriptCore version being used as `ArrayBuffer.prototype.byteLength` is not defined. Everything is working fine on iOS 11.

Not sure how to fix this. 🤔

**Comment by lucianomlima** [comment] 2020-06-28 01:18
Maybe need a polyfill like the following
https://gist.github.com/tjmehta/7e0f0d2aca966c71e70a453d0786f938

**Comment by charpeni** [comment] 2020-07-01 15:00
I would like to avoid the need of a polyfill, but it seems like this is coming from an issue within JavaScriptCore of iOS 10. So, we probably won't a choice here.

Polyfills are generally adding a significant footprint to the bundle size due to conditional imports not being supported, but I was able to find a good one here that seems high quality: https://polyfill.io/v3/polyfill.min.js?features=ArrayBuffer.

I'll retry with this later.

**Comment by charpeni** [comment] 2020-07-02 13:55
It's not working with those polyfills.

`byteLength` has to be an own property on the `ArrayBuffer` object, and in JavaScriptCore of iOS 10 and those polyfills, this is not the case.

Still investigating.

**Comment by charpeni** [comment] 2020-07-02 19:03
Fixed by #203 and will be released as `1.2.0-rc.1`.

**Closed** 2020-07-04 15:25 UTC
Labels: Bug, JavaScript Engine, whatwg-url
